# -*- coding: utf-8 -*-
"""FakeNewsDetector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h9mSGWTJAO7NHDrbhXqeCy-ev_BoB1Xd
"""

from sklearn.feature_extraction.text import TfidfVectorizer
text = ['Hello everyone! I am Pavini Jain, I love machine learning','Welcome to Fake News detector']

vect = TfidfVectorizer()

vect.fit(text)

print(vect.idf_)

print(vect.vocabulary_)

"""### word which is present in all the data will have low IDF. Hence unique words will be highlighted using the max IDF values"""

example = text[0]
example

example = vect.transform([example])
print(example.toarray())

### here, 0 is present in whohc indexed word, which is not available is given sentence.

"""#Passive Aggresive Classifier

Passive: if correct classification, keep the model<br>
Aggressive: if incorrect classification, update to adjust to this misclassified example<br><br>

Passive-Aggressive algorithms are generally used for large-scale learning. It is one of the few ‘online-learning algorithms‘. In online machine learning algorithms, the input data comes in sequential order and the machine learning model is updated step-by-step, as opposed to batch learning, where the entire training dataset is used at once. This is very useful in situations where there is a huge amount of data and it is computationally infeasible to train the entire dataset because of the sheer size of the data. We can simply say that an online-learning algorithm will get a training example, update the classifier, and then throw away the example.
"""

import os
os.chdir('D:/Fake News Detection')

import pandas as pd

df = pd.read_csv('news.csv')
df.head()

x = df['text']
y = df['label']

x

y

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
y_train

y_train

# max_df: https://stackoverflow.com/questions/27697766/understanding-min-df-and-max-df-in-scikit-countvectorizer
tfidf = TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_x_train = tfidf.fit_transform(x_train)
tfidf_x_test = tfidf.transform(x_test)

classifier = PassiveAggressiveClassifier(max_iter=50)
classifier.fit(tfidf_x_train,y_train)

y_pred = classifier.predict(tfidf_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy:{round(score*100,2)}%')

cf = confusion_matrix(y_test,y_pred,labels=['FAKE','REAL'])
print(cf)

def fake_news_det(news):
  input_data = [news]
  vectorized_input_data = tfidf.transform(input_data)
  prediction = classifier.predict(vectorized_input_data)
  print(prediction)

fake_news_det('U.S. Secretary of State John F. Kerry said Monday that he will stop in Paris later this week, amid criticism that no top American officials attended Sundayâ€™s unity march against terrorism.')

fake_news_det("""Go to Article 
President Barack Obama has been campaigning hard for the woman who is supposedly going to extend his legacy four more years. The only problem with stumping for Hillary Clinton, however, is sheâ€™s not exactly a candidate easy to get too enthused about.  """)

import pickle
pickle.dump(classifier,open('model3.pkl','wb'))

# Load the model from disk 
loaded_model = pickle.load(open('model3.pkl','rb'))

def fake_news_det1(news):
  input_data = [news]
  vectorized_input_data = tfidf.transform(input_data)
  prediction = loaded_model.predict(vectorized_input_data)
  print(prediction)

fake_news_det1("""Go to Article 
President Barack Obama has been campaigning hard for the woman who is supposedly going to extend his legacy four more years. The only problem with stumping for Hillary Clinton, however, is sheâ€™s not exactly a candidate easy to get too enthused about.  """)

fake_news_det1("""U.S. Secretary of State John F. Kerry said Monday that he will stop in Paris later this week, amid criticism that no top American officials attended Sundayâ€™s unity march against terrorism.""")

fake_news_det('''U.S. Secretary of State John F. Kerry said Monday that he will stop in Paris later this week, amid criticism that no top American officials attended Sundayâ€™s unity march against terrorism.''')